#!/bin/bash
# SPDX-License-Identifier: GPL-3.0
#
# Copyright (c) 2023 - Timothy Day <tday141@gmail.com>
#
# Fail on any error and source tims-tools. This should
# be enough to test the tims-tools script.
#

trap 'runtest-failure' ERR

#
# Function called on failure, used to log
# errors
#
function runtest-failure() {
    echo "Sourcing script failed!" > ./error.log
}

# Remove old error log, if there
rm -f ./error.log

set -Ee
source ./general/tims-tools

# If we have an error.log, we had an error
if [[ -f ./error.log ]]; then
    cat ./error.log
    rm -f ./error.log
    exit 1
fi
